-- Crear la base de datos
CREATE DATABASE EVENTOS_BBDD;
GO

USE EVENTOS_BBDD;
GO

-- Tabla TIPOS
CREATE TABLE TIPOS (
    ID_TIPO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(45) NOT NULL,
    DESCRIPCION NVARCHAR(200)
);
GO

-- Tabla USUARIOS
CREATE TABLE USUARIOS (
    USERNAME NVARCHAR(45) NOT NULL PRIMARY KEY,
    PASSWORD NVARCHAR(45) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    NOMBRE NVARCHAR(30),
    APELLIDOS NVARCHAR(45),
    DIRECCION NVARCHAR(100),
    ENABLED BIT NOT NULL DEFAULT 1,
    FECHA_REGISTRO DATE
);
GO

-- Tabla PERFILES
CREATE TABLE PERFILES (
    ID_PERFIL INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(45) NOT NULL
);
GO

-- Tabla USUARIO_PERFILES
CREATE TABLE USUARIO_PERFILES (
    USERNAME NVARCHAR(45) NOT NULL,
    ID_PERFIL INT NOT NULL,
    PRIMARY KEY (USERNAME, ID_PERFIL),
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES(ID_PERFIL)
);
GO

-- Tabla EVENTOS
CREATE TABLE EVENTOS (
    ID_EVENTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(200),
    FECHA_INICIO DATE,
    DURACION INT,
    DIRECCION NVARCHAR(100),
    ESTADO NVARCHAR(20) CHECK (ESTADO IN ('ACEPTADO', 'TERMINADO', 'CANCELADO')),
    DESTACADO CHAR(1) CHECK (DESTACADO IN ('S', 'N')),
    AFORO_MAXIMO INT,
    MINIMO_ASISTENCIA INT,
    PRECIO DECIMAL(9,2),
    ID_TIPO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPOS(ID_TIPO)
);
GO

-- Tabla RESERVAS
CREATE TABLE RESERVAS (
    ID_RESERVA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ID_EVENTO INT NOT NULL,
    USERNAME NVARCHAR(45) NOT NULL,
    PRECIO_VENTA DECIMAL(9,2),
    OBSERVACIONES NVARCHAR(200),
    CANTIDAD INT CHECK (CANTIDAD BETWEEN 1 AND 10),
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
    CONSTRAINT UQ_EVENTO_USER UNIQUE (ID_EVENTO, USERNAME)
);
GO
